import "./globals.css";
import { PermissionProvider } from '../context/PermissionContext';

export const metadata = {
  title: 'IntOffice',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <PermissionProvider>
      {children}
      </PermissionProvider>
      </body>
    </html>
  )
}
